CREATE TABLE COMPANY (
    CID INT PRIMARY KEY,
    CompanyName VARCHAR(255) NOT NULL,
    Admin_Contact VARCHAR(255) NOT NULL
);

CREATE TABLE LOCATION (
    LID INT PRIMARY KEY,
    CID INT NOT NULL,
    LocationName VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    FOREIGN KEY (CID) REFERENCES COMPANY(CID)
);

CREATE TABLE EMPLOYEE (
    UID INT PRIMARY KEY,
    LID INT NOT NULL,
    Username VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(64) NOT NULL, -- SHA256 hash is always 64 chars
    Email VARCHAR(255) NOT NULL UNIQUE CHECK (Email LIKE '%@%'),
    PointOfContact BOOLEAN NOT NULL DEFAULT FALSE,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    FOREIGN KEY (LID) REFERENCES LOCATION(LID)
);

CREATE TABLE SCAN (
    Scan_ID INT PRIMARY KEY CHECK (Scan_ID >= 1000), -- ensures length of 4 digits
    LID INT NOT NULL, 
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    IP_Address VARCHAR(45) NOT NULL,
    OS VARCHAR(255) NOT NULL,
    Open_Ports TEXT NOT NULL, -- Text is used for large string data
    FOREIGN KEY (LID) REFERENCES LOCATION(LID)
);