CREATE TABLE COMPANY (
    CID INT PRIMARY KEY,
    CompanyName VARCHAR(255) NOT NULL,
    Admin_Contact VARCHAR(255) NOT NULL
);

CREATE TABLE LOCATION (
    LID INT PRIMARY KEY,
    CID INT NOT NULL,
    LocationName VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    FOREIGN KEY (CID) REFERENCES COMPANY(CID)
);

CREATE TABLE EMPLOYEE (
    UID INT PRIMARY KEY,
    LID INT NOT NULL,
    Username VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PointOfContact BOOLEAN NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    FOREIGN KEY (LID) REFERENCES LOCATION(LID)
);

CREATE TABLE SCAN (
    Scan_ID INT PRIMARY KEY,
    LID INT NOT NULL,
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    IP_Address VARCHAR(45) NOT NULL,
    OS VARCHAR(255) NOT NULL,
    Open_Ports VARCHAR(255) NOT NULL,
    FOREIGN KEY (LID) REFERENCES LOCATION(LID)
);